server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}

    gateway:
      routes:
        - id: order-route
          uri: http://localhost:9000
          predicates:
            - Path=/provider/get/**

        - id: order-route2
          uri: http://localhost:9001
          predicates:
            - Path=/provider/get/**

        - id: consumer-route3
          uri: http://localhost:8081
          predicates:
            - Path=/consumer/**

        - id: consumer-route4
          uri: http://localhost:8081
          predicates:
            - Path=/openFeign/**