server:
  port: 9001


spring:
#  application:
#    name: provider-order
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        service-name: ${spring.application.name}
  datasource:
    url: jdbc:mysql://localhost:3306/2022_springcloud?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # 处理时间
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  profiles:
    active: dev



mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.wsj.pojo
  configuration:
    map-underscore-to-camel-case: true




# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径,输入http:localhost:8080/swagger-ui.html会自动重定向到swagger页面
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs    #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs:
    - group: 'default'   #分组名称
      paths-to-match: '/**'   #配置需要匹配的路径,默认为/**
      packages-to-scan: com.wsj    #配置要扫描包的路径,一般配置到启动类所在的包名
#packages-to-scan一定要记得修改-------------------------------------------------------------------

# knife4j的增强配置，不需要增强可以不配(建议配置一下)
knife4j:
  enable: true    #开启knife4j,无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文
    swagger-model-name: 实体类列表   #重命名SwaggerModel名称,默认

swagger3:
  name: wsj团队
  email: whiskeyaka9@gmail.com
  title:
  description:
  version: 1.0
  termsOfServiceUrl: https://www.baidu.com